### ISSUE TITLE
Official logo or banner

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette-starlette#27]
[`tartiflette-aiohttp`](https://github.com/dailymotion/tartiflette-aiohttp) has a banner displayed at the top of its README (see below). Having an equivalent one for `tartiflette-starlette` would be nice to enhance the attractiveness of the repo.

Related to #20 

@tsunammis Do you or someone else at Dailymotion still have the art files for the banner? I can make a `tartiflette-starlette` version. :-)

![](https://github.com/tartiflette/tartiflette-aiohttp/raw/master/github-landing.png)

**Comment by tsunammis** [comment]
I can make it easily and quickly. Do you have the starlette SVG logo?

**Comment by florimondmanca** [comment]
There is an SVG version of the logo here: [koddr/starlette-logo](https://github.com/koddr/starlette-logo/blob/master/src/light/svg/starlette__full_logo__without_text__light.svg), licensed under CC 1.0.

By the way, I think the term "ASGI" should appear somewhere in the banner. We definitely don't want users to think this is just for Starlette, and then look away. So something like:

```
Tartiflette. + Starlette
Python GraphQL Engine over HTTP (ASGI)
```

**Comment by tsunammis** [comment]
![Tartiflette-starlette](https://user-images.githubusercontent.com/158689/58954519-b05ad680-8799-11e9-9134-90622e7731f3.png)

Here is the image ;-)

**Comment by florimondmanca** [comment]
Awesome! Added to #26 :+1:
