### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette-starlette#3]

**Comment by florimondmanca** [comment]
@tsunammis I think we can already publish a first release to PyPI, even though this will install Starlette's 0.12 beta. I don't think it is an issue — the goal is to get a first release out there, and we can publicly communicate on this project later.

I configured a `pypi` deploy in TravisCI to publish releases on tagged commits on master. Publishing to PyPI requires passing PyPI credentials via CI environment variables. Should I use mine, or do we plan to give the Tartiflette org official PyPI credentials (which the org's admin would manage)?

**Comment by tsunammis** [comment]
We will plan a migration to a specific tartiflette user. Right now, you can publish by yourself.

As this version is still in beta, please feature it on the README as an unstable/beta version.

**Comment by florimondmanca** [comment]
Okay. I'll add a beta notice on the README. :+1:

**Comment by florimondmanca** [comment]
I'll close this since tartiflette-starlette was successfully released to PyPI recently.
