### ISSUE TITLE
Tartiflette 0.12 compatibility

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette-starlette#32]
**Problem description**

> Note: `tartiflette-starlette` is currently pinned to `tartiflette<0.11`.

I noticed that Tartiflette 0.11 was out, and there are a few changes.

The major one I see is that engine creation is now **asynchronous** and must be done via `create_engine()`.

This means that the current `engine` parameter to `TartifletteApp()` isn't appropriate anymore, because we can't create a raw `Engine` anymore (at least not in a sync context which is typically where the app is registered).

**Alternatives**

First, options previously delegated to `Engine` must now be handled by `TartifletteApp`. This can be done in two ways:

1. Create new keyword parameters on `TartifletteApp` (similar to what `tartiflette-aiohttp` currently does things), store them and then pass them to `create_engine()`.
2. Provide an `Engine` helper and pass its kwargs down to `create_engine()`.

> Supported keyword arguments should be at least `sdl`, `schema_name` and `modules` (IMO). Supporting all those supported by `create_engine()` would be best.

I personally prefer 2) because it keeps things organized and is more explicit/IDE-friendly.

Next, we're going to have to defer engine creation/"cooking" to when the app starts up. This can be implemented with Starlette's `Lifespan` helper.

**Additional context**
- [0.11 (Changelog)](https://github.com/tartiflette/tartiflette/blob/master/changelogs/0.11.0.md)
- https://tartiflette.io/docs/api/engine

**Comment by florimondmanca** [comment]
Hi @abusi, ccan I ask why it is now impossible to create an engine synchronously — or rather, what makes creating an engine asynchronously necessary? Thanks!

**Comment by abusi** [comment]
Hi @florimondmanca I was in the process of making starlette compatible with 0.11 by passing a partial as a startup hanlder and then do the `create_engine` in it. 

We removed the parameters from the engine cause they are not needed by the engine itself but by subcomponent, it was bothering me to add things to self that weren't usefull for self. They are all transitive parameters that's why I moved them to the `.cook` method.

I understand your frustration here and I didn't think it would be such a big deal.
In the future we'll try to discuss these kind of thing with you before doing them. That's also why we are not in v1.0.0 it's because things are moving fast. 

I'll propose a PR to you with tartiflette 0.11 compatibility, I didn't had the time to finish it, but I'll do it as soon as I can (in the coming days).

**Comment by florimondmanca** [comment]
Thanks for your answer!

> That's also why we are not in v1.0.0 it's because things are moving fast.

Yup, and you're 100% right!

> I understand your frustration here and I didn't think it would be such a big deal.

I'm not angry at all about the change, just trying to understand the decision. :-) Sorry if it came across as rough!

> In the future we'll try to discuss these kind of thing with you before doing them.

Thanks! Just a heads up in the associated Tartiflette issue/PR would be enough, I wouldn't want to slow things down.

> I was in the process of making starlette compatible with 0.11 by passing a partial as a startup hanlder and then do the create_engine in it.

FYI, I pushed a complete overhaul of the internals of `TartifletteApp` yesterday, which allow us to leverage Starlette's components much more easily.

Here's my idea for an updated `TartifletteApp`:

```python
from starlette.routing import Lifespan

class TartifletteApp:
    def __init__(
        self,
        sdl: str,
        *,
        graphiql: typing.Union[bool, GraphiQL] = True,
        path: str = "/",
        schema_name: str = "default",
        modules: typing.List = None,
    ):
        if graphiql is True:
            graphiql = GraphiQL()

        routes = []

        if graphiql and graphiql.path is not None:
            routes.append(Route(path=graphiql.path, endpoint=GraphiQLEndpoint))

        graphql_route = Route(path=path, endpoint=GraphQLEndpoint)
        routes.append(graphql_route)

        self.engine = Engine()

        self.app = Lifespan(GraphQLMiddleware(
            Router(routes=routes),
            engine=self.engine,
            graphiql=graphiql,
            graphql_path=graphql_route.path,
        ))

        @self.app.on_event("startup")
        async def prepare_engine():
            await self.engine.cook(
                sdl=sdl, modules=modules, schema_name=schema_name
            )

    async def __call__(self, scope: Scope, receive: Receive, send: Send):
        await self.app(scope, receive, send)
```

**Comment by florimondmanca** [comment]
By the way, note that the `sdl`, `schema_name`, and `modules` parameters are just used by `.cook()`.

If we were able to pass an `Engine` with those parameters stored in its `self`, it would lead to **more decoupled code** because `tartiflette-starlette` wouldn't need to care about the `cook` interface at all — the `Engine` would.

Here's how it could simplify `TartifletteApp.__init__()`:

```python
    def __init__(
        self,
        engine: Engine
        *,
        graphiql: typing.Union[bool, GraphiQL] = True,
        path: str = "/",
    ):
        if graphiql is True:
            graphiql = GraphiQL()

        routes = []

        if graphiql and graphiql.path is not None:
            routes.append(Route(path=graphiql.path, endpoint=GraphiQLEndpoint))

        graphql_route = Route(path=path, endpoint=GraphQLEndpoint)
        routes.append(graphql_route)

        self.engine = engine

        self.app = Lifespan(GraphQLMiddleware(
            Router(routes=routes),
            engine=self.engine,
            graphiql=graphiql,
            graphql_path=graphql_route.path,
        ))

        self.app.add_event_handler("startup", self.engine.cook)
```


I insist because while I can see how storing data in `self` is not directly useful to the `Engine`, it would turn the `Engine` into an object that can be passed around, ready for cooking by third-party clients such as `tartiflette-starlette`. Starlette uses this compositional approach a lot, and I think it makes the API extremely pleasant and explicit IMO.

Is it too late to consider a switch?

**Comment by abusi** [comment]
You're making good points, with this, let me think about it a little bit more. I'll get back to you during the day.

**Comment by abusi** [comment]
https://github.com/tartiflette/tartiflette/pull/244 @florimondmanca You were right, it gives us more flexibility.
Thank you for your feedback.

**Comment by abusi** [comment]
@florimondmanca Do you still need help with the 0.11.x migration ? I don't have time to finish my work on it, I see that you already have ideas for it. If you think it can wait a bit, i'll do it next week.

**Comment by florimondmanca** [comment]
I think I can take it over. Feel free to push your work to a branch and I'll be able to take it from there this week/this weekend. :-) Thanks!
