### ISSUE TITLE
Getting 307 temporary redirect running ASGI submounting example

### ISSUE THREAD

**Issue by shalseban** [tartiflette/tartiflette-starlette#43]
I am trying to run the ASGI submounted Tartiflette example using starlette and on hitting the endpoint using: 

`curl -H "Content-Type: application/graphql"  -d '{ hello(name: "Chuck") }' http://localhost:8000/graphql`

I receive code `307`. 

I tried running it through grapiql, while the the UI loads, it fails to load the schema, looks like it is hitting the root path `/` and returning with `405`.  

The standalone example works fine.

**Comment by florimondmanca** [comment]
Hey, thanks for reporting this!

I don’t have much time to try this out locally, but first the 307 issue can you confirm that adding a trailing slash gives you a 200? Starlette automatically appends and redirects trailing slashes to route URLs by by default. I believe this is worth a note in the README?

As for the wrong GraphiQL endpoint path, it looks like a bug. TartifletteApp should automatically prepend any root path present in the ASGI scope. Feel free to investigate a bit if you can, I’ll try and take a look soon as well. :)

**Comment by shalseban** [comment]
@florimondmanca Ah, yes, regarding the `307` the trailing slashes worked. Interesting. 

I did take a cursory look into GraphiQL part of it yesterday. The `GraphiQL` object attached to the `TartifletteApp` is initialized with `path=None`. Not sure if that is expected yet. I can dig into it further later tonight. 

I guess the `307` and `GraphiQL` are both separate issues, I can create a separate issue for the `GraphiQL` one and close this one.

**Comment by florimondmanca** [comment]
Thanks @shalseban. I opened #44 to add a note about the 307 you've encountered. :-)

I looked at the `GraphQL` issue and there's something really wrong — most tests aren't even passing anymore. I'm taking a look.
