### ISSUE TITLE
Tartiflette 1.0 compatibility

### ISSUE THREAD

**Issue by shalseban** [tartiflette/tartiflette-starlette#49]
Not compatible with `tartiflette` `1.0`.

**Comment by florimondmanca** [comment]
Yup, that’s why Tartiflette is currently pinned to 0.13 and below here.

Can you provide more context on which pieces aren’t compatible?

**Comment by shalseban** [comment]
Whoops. That was incorrect wording on my part. What I meant could we remove the pinning? unless you see compatibility issues. I just wanted to use some of the new features that rolled out in `1.0` (TypeResolver)

**Comment by florimondmanca** [comment]
I see, thanks! If you're up for it, I'd accept a PR upgrading the pin to `>=0.12, <1.1` in `setup.py`. If CI tests pass, we'll be good to release with official 1.0 support. :)
