### ISSUE TITLE
What to do for version 0.6.0?

### ISSUE THREAD

**Issue by AutumnalDream** [tartiflette/tartiflette-starlette#78]
What do we need to do to get 0.6.0 out?

**Comment by florimondmanca** [comment]
Hi @AutumnalDream, thanks for your interest in this project. :)

So, for 0.6 we need to resolve the following items:

- [x] Tartiflette 1.x failed to build in some cases (e.g. on macOS Mojave / Python 3.7) - https://github.com/tartiflette/tartiflette/issues/301 - Resolved in [Tartiflette 1.1.1](https://github.com/tartiflette/tartiflette/blob/master/changelogs/1.1.1.md)
- [ ] Give a final review to and merge #58 - Tartiflette 1.x support

I'll take a look at #58 soon.

**Comment by florimondmanca** [comment]
0.6.0 was released just now :tada: -> https://pypi.org/project/tartiflette-starlette/0.6.0
