### ISSUE TITLE
Rename the application "Tartiflette" to something more suited like TartifletteHandler?

### ISSUE THREAD

**Issue by tsunammis** [tartiflette/tartiflette-starlette#9]
Hello,

The `Tartiflette` class exposed in `tartiflette_starlette` could be confusing for the developer with the official package `tartiflette`. Is it possible to rename it to something more suited?

In this following use-case, `Tartiflette(sdl=...)` act as a handler, doesn't it?

```python
app = Starlette()
app.add_route("/graphql", Tartiflette(sdl=sdl))
```

Maybe a better naming should be `TartifletteHandler`. What do you think?

**Comment by florimondmanca** [comment]
Yes, that's a very valid point!

How about `TartifletteApp` — similarly to how Starlette uses `GraphQLApp` for its Graphene app? It would be even clearer that this represents an ASGI *app*.

**Comment by tsunammis** [comment]
👍 for `TartifletteApp`
